plugins {
    id 'groovy'
    id 'java'
    id 'application'
}

application {
    mainClass = 'todolist.Main'
}

group = 'todolist'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.apache.groovy:groovy:4.0.16'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    testImplementation 'org.spockframework:spock-core:2.3-groovy-4.0'
    testImplementation 'net.bytebuddy:byte-buddy:1.14.10'
}

run {
    standardInput = System.in
}

test {
    useJUnitPlatform()
}